### ISSUE TITLE
Show UI feedback when timer idles

### ISSUE THREAD

**Issue by pmarsceill** [josh/Aware#12]
There should be some visual indication that the timer has paused and started idling. Possible implementations:
- dim the time count's alpha
- display an icon
- a combination of the above

**Comment by josh** [comment]
Yeah, I dig a simple opacity change. Currently, once the idle time is hit, the clock will reset and be paused at "0 min". It could then stay dimmed until we actually start the clock again. 

In terms of implementation, the current button just uses the system's font rendering stack. So it should be pretty easy to set a alpha/opacity property on that. Note to self, remember to test both the light and dark menu bars with this change.
