### ISSUE TITLE
Custom Domain

### ISSUE THREAD

**Issue by josh** [josh/Aware#19]
After reviewing https://github.com/josh/Aware/pull/18, I'm wondering if we need a custom domain.

Right now, our `gh-pages` branch would be hosted at `https://josh.github.io/aware`. We'd use this page as the "Marketing URL" and "Support URL"s.

The domain also affects our "Bundle ID" which is a reverse domain, currently `com.github.josh.Aware`. Once the App is published, we can no longer change this.
## 

CC: @pmarsceill

**Comment by pmarsceill** [comment]
@josh I think we need a custom domain.

Interestingly enough: http://aware.menu is available though not sure how that would translate to a Bundle ID.

**Comment by pmarsceill** [comment]
Here is the Hover search:

https://www.hover.com/domains/results?utf8=✓&q=aware.menu

**Comment by josh** [comment]
> Interestingly enough: http://aware.menu is available though not sure how that would translate to a Bundle ID.

As for the Bundle ID, that'd still be fine, `menu.aware.Aware`.

But those custom TLD are kinda pricey, $30 a year! `awaremenu.com` itself is available for $12. Trying to think of some longer suffixes. `awareapp.com` is taken.

**Comment by josh** [comment]
Ideas:
- awaremac.com
- awareosx.com
- awaremenu.com
- awaremenuapp.com
- awaremenubar.com
- awaretimer.com

**Comment by pmarsceill** [comment]
I'll get on setting up th gh-pages site today. FWIW I like awaremac, awaretimer, or awaremenu (in no particular order).
