### ISSUE TITLE
Polish up app icon

### ISSUE THREAD

**Issue by pmarsceill** [josh/Aware#26]
The icon is cool, but it could be cooler with a little more polish. I'd like to do the following before our official launch.
- [x] Explore adding reflection to monitor to make it seem more like a monitor
- [x] Explore different gradient colors / background treatments on the monitor
- [x] Try adjusting small screen versions for better viewing at small sizes on non-retina displays
- [x] Play with the stroke width a bit on the eye / clock
- [x] Add updated icon to app.

**Comment by pmarsceill** [comment]
Here is an updated version, any thoughts?

![aware icon](https://cloud.githubusercontent.com/assets/896475/13063640/27e7f6ee-d418-11e5-8527-dd50aa4e2192.png)

**Comment by pmarsceill** [comment]
More twerking to get the lighting right:

![aware icon](https://cloud.githubusercontent.com/assets/896475/13063790/92ef23f8-d419-11e5-83b0-fc3406939d4f.png)

**Comment by josh** [comment]
On the original and second icon posted here, I kinda like that the bezel is more transparent and the gradient bleeds in subtly. Ha, I'm not even sure if you actually changed that.

I dig the overall changes though.

**Comment by pmarsceill** [comment]
More tweaks:

![aware icon](https://cloud.githubusercontent.com/assets/896475/13083256/3741147e-d4a2-11e5-8b85-f4d15f3be771.png)

**Comment by josh** [comment]
I like the shape adjust 😁

I feel like you're making me guess at what you're tweaking! Good exercise!

**Comment by pmarsceill** [comment]
> I feel like you're making me guess at what you're tweaking! Good exercise!

Ha, yeah wanted it to feel more like a monitor. Also adjusted the bezel and added some subtle highlights to the bottom to define it a bit more.

**Comment by pmarsceill** [comment]
Closed via #29
