### ISSUE TITLE
Assets dir on master or another orphan branch?

### ISSUE THREAD

**Issue by pmarsceill** [josh/Aware#27]
@josh should I move the `/Assets` directory from `master` to another orphan branch so it doesn't get published with each release? I feel like it should be here, but probably not on `master`.

**Comment by josh** [comment]
Its not tracked in Xcode, so it won't be included in the binary. So its not hurting anything. I think its fine in `master`.

For an example, if you revised the the icon, a PR to `master` would probably include a change to the master `.sketch` as well as regenerated static `.appiconset` files.

**Comment by pmarsceill** [comment]
>  So its not hurting anything. I think its fine in `master`.

:+1:
