### ISSUE TITLE
Allow alternate time format in menu

### ISSUE THREAD

**Issue by pmarsceill** [josh/Aware#3]
Right now the menu displays in `Xm` format.

![image](https://cloud.githubusercontent.com/assets/896475/11872842/81b706c6-a4a5-11e5-86f6-3d2f209e23aa.png)

If I'm working for more than a 200 or so minutes I have to do math (ugh) to figure out how many hours this is. Would it be beneficial to allow users to switch the to HH:MM (or automatically switch it after 60m)?

**Comment by josh** [comment]
I thinking of formatting the hour time as `1h 15m`.

Originally was always using `HH:MM` but it looked to much like the clock.

Totally up to consider other formatting options if you have more ideas. Distinction from the current time was my only concern.

**Comment by pmarsceill** [comment]
`1h 15m` is :ok_hand:
