### ISSUE TITLE
App Store Screenshots

### ISSUE THREAD

**Issue by josh** [josh/Aware#31]
<img width="1009" alt="screen shot 2016-02-18 at 7 53 50 pm" src="https://cloud.githubusercontent.com/assets/137/13166155/5c37b14c-d679-11e5-930c-4e4855a00de7.png">

https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Appendices/Properties.html

Up to 5 screenshots can be posted. 1 is required.

(Reminder from Slack conversation with @pmarsceill)

**Comment by pmarsceill** [comment]
@josh here are some screen shots, did some different BGs and menubar colors.

https://www.dropbox.com/sh/cgh6hcjmh492tm7/AADcSkavT_nlX6epfdMUoqCxa?dl=0

I couldn't attach the originals bc they were too big but her is a preview:

![screen shot 2016-02-22 at 12 27 58 pm](https://cloud.githubusercontent.com/assets/896475/13226541/d64a07f8-d95f-11e5-8c81-9fd66310b469.png)
![screen shot 2016-02-22 at 12 28 03 pm](https://cloud.githubusercontent.com/assets/896475/13226542/d64fdab6-d95f-11e5-924f-3f8a527543d0.png)

**Comment by josh** [comment]
Hella retina!
