### ISSUE TITLE
Incorrect system time shown on marketing site.

### ISSUE THREAD

**Issue by pmarsceill** [josh/Aware#32]
Not that this is a show stopper, but my system time shows:

<img width="261" alt="screen shot 2016-02-22 at 12 03 02 pm" src="https://cloud.githubusercontent.com/assets/896475/13225758/3daaf2ee-d95c-11e5-911c-46c8c53ec6e5.png">

and the website shows:

<img width="1052" alt="screen shot 2016-02-22 at 12 03 46 pm" src="https://cloud.githubusercontent.com/assets/896475/13225784/5f354e00-d95c-11e5-8ac5-dcf38e7a5a82.png">

AM / PM is incorrect and 12 is displayed as 0.

**Comment by josh** [comment]
doh! good catch
