### ISSUE TITLE
Can't find the .app file in the release

### ISSUE THREAD

**Issue by jteneycke** [josh/Aware#38]
Is the release itself the .app file? I tried renaming the extracted zip, but no dice.

**Comment by josh** [comment]
Only the source code is available. We're in the process of releasing the binaries on the Mac App Store.

**Comment by jteneycke** [comment]
![screen shot 2016-04-03 at 9 17 56 pm](https://cloud.githubusercontent.com/assets/1854148/14236334/afbd780c-f9e1-11e5-90aa-be71b60aa659.png)

So the current instructions from the README will be true once it's published to the app store?

**Comment by josh** [comment]
I'll remove that as soon as I have the App Store link. Thanks.
