### ISSUE TITLE
Let's make an app icon

### ISSUE THREAD

**Issue by pmarsceill** [josh/Aware#4]
Here's a quick concept:

![image](https://cloud.githubusercontent.com/assets/896475/11876103/edca4c5a-a4b5-11e5-9f80-31a0b5b7962e.png)

![image](https://cloud.githubusercontent.com/assets/896475/11876131/1504f720-a4b6-11e5-80dc-6cf428a2faef.png)

![image](https://cloud.githubusercontent.com/assets/896475/11876195/66da505e-a4b6-11e5-9bea-c06594c2d1f8.png)

**Comment by pmarsceill** [comment]
Maybe rounded rect is better:

![image](https://cloud.githubusercontent.com/assets/896475/11876269/d1320eec-a4b6-11e5-98c9-e63182c48708.png)

**Comment by pmarsceill** [comment]
Refined this a bit more so it didn't look so iOS-y... What if the frame was the actual monitor?

![image](https://cloud.githubusercontent.com/assets/896475/11881105/a7633520-a4d2-11e5-95e0-bd0c5a8ed31f.png)

**Comment by josh** [comment]
HELL YEAH

**Comment by pmarsceill** [comment]
I'll post all the files as an attachment here, since I don't have write access to this repo.

**Comment by josh** [comment]
> I'll post all the files as an attachment here, since I don't have write access to this repo.

Just added you as a collaborator.

**Comment by pmarsceill** [comment]
:D thanks. I'll get this into a PR.

**Comment by pmarsceill** [comment]
![icon_256x256](https://cloud.githubusercontent.com/assets/896475/12147215/c598f528-b465-11e5-8b69-02b5cf823f06.png)
