### ISSUE TITLE
Icon update

### ISSUE THREAD

**Issue by pmarsceill** [josh/Aware#44]
@josh I've been working on some icon updates for the next release, what are your thoughts on this type of thing?

<img src="https://cloud.githubusercontent.com/assets/896475/19022622/36726194-88aa-11e6-8e24-6dbd5482f6c8.png" alt="aware-icon" width="128" height="128">

Trying to convey time passing on a computer without being so literal.

**Comment by pmarsceill** [comment]
Tweaked the lighting and mountain ranges a bit..

<img src="https://cloud.githubusercontent.com/assets/896475/19022990/b7b6b29e-88b1-11e6-8390-b142d7d922be.png" alt="aware-icon" width="128" height="128">

**Comment by josh** [comment]
Oh, nice!

What are you thinking for the mini icon? I actually like it more than the current large size.

<img width="120" alt="screen shot 2016-10-02 at 1 18 01 pm" src="https://cloud.githubusercontent.com/assets/137/19023399/e97a5a88-88a2-11e6-86f9-15fb36da21bd.png">

**Comment by pmarsceill** [comment]
Totally forgot about the small guy. I agree, the circular icon works better at larger sizes, too.  Here is a concept that merges the sunrise/sunset + stars with the clock. I did a very Apple-y thing and modled it after the Braun BNC001 alarm clock:

<img src="https://cloud.githubusercontent.com/assets/896475/19049990/9dd65572-897a-11e6-99a1-7b83db895cc7.png" alt="aware-icon" width="512" height="512">

<img src="https://cloud.githubusercontent.com/assets/896475/19049990/9dd65572-897a-11e6-99a1-7b83db895cc7.png" alt="aware-icon" width="256" height="256">

<img src="https://cloud.githubusercontent.com/assets/896475/19049990/9dd65572-897a-11e6-99a1-7b83db895cc7.png" alt="aware-icon" width="128" height="128">

**Comment by josh** [comment]
> I did a very Apple-y thing and modled it after the Braun BNC001 alarm clock:

Hot. Lets 🚢
