### ISSUE TITLE
Move website to HTTPS

### ISSUE THREAD

**Issue by pmarsceill** [josh/Aware#49]
Gotta do it.

**Comment by josh** [comment]
Is *you know what* enabled for public gh-pages repositories yet?

**Comment by pmarsceill** [comment]
> Is you know what enabled for public gh-pages repositories yet?

No, but we _could_ move hosting over to Netlify 😆

**Comment by josh** [comment]
I’d rather avoid additional dependencies if *someday* this will just work. But Netlify does look pretty rad though!

**Comment by josh** [comment]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by josh** [comment]
"Domain awaremac.com is not eligible for HTTPS at this time." 🤔 I'll try again later.

**Comment by josh** [comment]
https://awaremac.com
