### ISSUE TITLE
Aware doesn't reset the timer when computer is unlocked (no sleep)

### ISSUE THREAD

**Issue by ahindle** [josh/Aware#50]
# Prerequisites

When I unlock Mac OS after locking it using `CMD + CONTROL + Q` Aware's timer is not reset to 0m.
Note: The computer isn't put to sleep, just locked.

# Expected Behaviour

Timer reset to 0m when I unlock Mac Os.

# Current Behaviour

Timer not been reset.

## Steps to Reproduce

1. Prevent your OS from going to sleep in the Preferences.
2. Start Aware
3. Lock Mac OS using `CMD + CONTROL + Q`
4. Wait
5. Unlock
6. See in the menu bar that Aware isn't showing 0m.

```
MacBook Pro (15-Inch, 2017)
Mac OS version: 10.13.4  
```
Let me know if you need anything else.

**Comment by josh** [comment]
Hey @ahindle, thanks for opening this issue. I never tested with `CMD + CONTROL + Q` so it's definitely something I overlooked.

Right now Aware listens for "screen wake" events to reset the timer. However, those don't seem to run on lock/unlock if the screen is always on. I thought there would another for "did lock/unlock" but I couldn't seem to get any to work. I looked into both [sessionDidBecomeActiveNotification](https://developer.apple.com/documentation/appkit/nsworkspace/1525293-sessiondidbecomeactivenotificati) and [willPowerOffNotification](https://developer.apple.com/documentation/appkit/nsworkspace/1532954-willpoweroffnotification) but neither worked.

I'm not sure if this is possible to detect. Let me know if you have any ideas! Thanks!
