### ISSUE TITLE
Timer resetting while watching movies or youtube

### ISSUE THREAD

**Issue by gusals3587** [josh/Aware#51]
### Bug
While watching long youtube videos or any kind of video, if there weren't any user activity for more than a couple of minutes, the timer reset to 0, defeating the purpose of tracking user's time with the computer
### Speculation
Looking at the code, it appears that in the updateButton function, there appears to be a condition that if the user was not entering any keys, moving, clicking, or scrolling with the mouse for more than 120 seconds (or 2 minutes) the timer resets
### Temporary Fix
Removing this
``` swift
if (self.sinceUserActivity() > userIdleSeconds) {
    timerStart = Date()
    idle = true
} ...
```
does seems to stop the timer from resetting, however I do not know the implication that might be involved in removing that if block

Any suggestions on how to solve this?

**Comment by josh** [comment]
Checking for mouse movements is part of the current App design. I'll keep an eye out for APIs that could tell if you're computer is playing back video to keep the timer from reseting. Thanks!
