### ISSUE TITLE
The app is no longer available on the UK mac app store

### ISSUE THREAD

**Issue by joshvince** [josh/Aware#52]
When you try to visit the mac app store from your homepage from the UK, you get the following error when it opens the app store.

>The item you requested is not currently available in the UK store

I'd love to recommend it, but an app that has to log keystrokes and mouse moves to work, but is revoked from the app store will naturally raise red flags in people's minds!

**Comment by gusals3587** [comment]
+1 Unavailable in Korea mac app store, and America app store as well, I think it just got pulled off from the mac app store worldwide

**Comment by tjluoma** [comment]
It was not just removed from the Mac App Store, it was removed from my list of purchases. That's highly unusual and will raises suspicions as well, although I suspect the truth is not something nefarious but probably just some App Store policy or some such. I hope that's all it is!

**Comment by josh** [comment]
There's no privacy issue. I just forgot to pay Apple the $100 developer membership. It should be back up soon. Until then you can download it directly from GitHub https://github.com/josh/Aware/releases/download/v1.0.3/Aware.zip

**Comment by tjluoma** [comment]
I didn't really think there would be something evil in an app whose code is published on GitHub for everyone to see! But I can't believe Apple would remove the download from my Purchase history for _that!_ Seems petty. Anyway, thanks for letting us know.

**Comment by josh** [comment]
> I didn't really think there would be something evil in an app whose code is published on GitHub for everyone to see!

Feel free to compile the source code yourself then!

> But I can't believe Apple would remove the download from my Purchase history for _that!_ Seems petty.

Yeah, that is annoying. Sorry about that. I'm able to download old iOS apps after the developer delists them--maybe it only applies to the Mac app store.

**Comment by tjluoma** [comment]
>> I didn't really think there would be something evil in an app whose code is published on GitHub for everyone to see!
>
> Feel free to compile the source code yourself then!

I did that last night! Actually got the newer-than-release version! I feel _fancy_ :-)
