### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by Tvax** [josh/Aware#66]
Display a notification every time 30 minutes (or any adjustable time) is reached to remind the user to take a break.

**Comment by josh** [comment]
Hey @Tvax, thanks for the request! But I think we're going to keep Aware quiet. I think there' some other's other there that provide alarm options.

> There are no assumptions made as to what you do with this information. No popups or alarms to tell you to take a break, just a record of time tracked in your menubar for easy access.

😁
