### ISSUE TITLE
Configurable sound reminder

### ISSUE THREAD

**Issue by dbogdanov** [josh/Aware#67]
I've just found this app and started using it as a nice replacement for [Awareness](http://iamfutureproof.com/tools/awareness/), which isn't maintained. Thanks!! 

One very useful feature that Awareness has is simple sound notifications at configurable times (e.g., every hour).  I understand this may be out of the original scope of this app, but it would be an amazing feature to have. 

UPD: I see this feature request is already addressed in #66.

**Comment by josh** [comment]
Ah, yes, I think we’re going to avoid any sounds.

But I do wish I could recommend a better replacement than Awareness for sounds. I’m not sure it’s exactly the same, but there [a ton of these Pomodoro timer apps](https://zapier.com/blog/best-pomodoro-apps/) for setting up work intervals and break alarms. Maybe one of those could work better for you.

Thanks for your suggestion though!
