### ISSUE TITLE
Start at login menu item

### ISSUE THREAD

**Issue by josh** [josh/Aware#7]
Add shortcut to toggle "Start at login" from menu.

**Comment by josh** [comment]
Ugh, Apple is terrible.

The old "Shared File List" APIs do exactly what I want, but are now deprecated in 10.10 and apparently Apple will not allow them to be used in the Mac App Store either. Theres this other "Service Management Framework" that is recommended by Apple for sandbox apps, but many of the SM APIs for querying services list are also now deprecated.

Maybe 10.12 will provide new APIs. Sigh.

**Comment by trevorturk** [comment]
🍎 💩 ... 🕚 🌄
