### ISSUE TITLE
MacOS 15 Sequoia, 0m changed to 0min

### ISSUE THREAD

**Issue by rewhex** [josh/Aware#79]
Hello, after update I see this, instead of 3m.
<img width="87" alt="Screenshot 2024-09-17 at 11 57 06 PM" src="https://github.com/user-attachments/assets/a2644254-55d7-44a1-bdde-f42e361a69ed">

**Comment by josh** [comment]
Hey @rewhex, the time format is now configurable. If you click the time and go into Settings, you can choose between multiple formatting options. Hope that helps!

**Comment by rewhex** [comment]
Hello, sorry but I can't find this settings, can you please show where it is?
